//! SUMO traffic simulator network I/O.
//!
//! Imports SUMO `.net.xml` files and exports [`Project`]s back to the SUMO
//! network format. SUMO networks use a flat Cartesian coordinate system (metres)
//! and describe roads as directed `<edge>` elements containing one or more
//! `<lane>` children, joined at `<junction>` nodes.
//!
//! ## Mapping
//!
//! - Each non-internal `<edge>` becomes a [`Road`]. The road reference line is
//!   taken from the edge `shape` polyline (falling back to the lane shapes).
//! - Edge lanes become OpenDRIVE right-side driving lanes: SUMO lane `index = i`
//!   maps to lane id `-(i + 1)`, preserving lane count and per-lane width.
//! - Internal edges/junctions (id starting with `:` or `function="internal"`)
//!   are skipped — they are regenerated by SUMO's `netconvert`.
//!
//! ## Limitations
//!
//! Junction connectivity and traffic-light programs are not yet round-tripped;
//! geometry, lane counts, lane widths and speeds are.

use quick_xml::Reader;
use quick_xml::events::{BytesStart, Event};
use we_core::geometry::eval::evaluate_geometry;
use we_core::model::{
    Geometry, GeometryType, Lane, LaneSection, LaneType, LaneWidth, Project, Road,
};

/// Default lane width (metres) when a SUMO lane omits its `width` attribute.
const DEFAULT_LANE_WIDTH: f64 = 3.2;
/// Default lane speed (m/s) used on export when a road has no speed.
const DEFAULT_SPEED: f64 = 13.89;

/// Error type for SUMO I/O operations.
#[derive(Debug, thiserror::Error)]
pub enum SumoError {
    /// The input could not be parsed as a SUMO network.
    #[error("invalid SUMO network: {0}")]
    Parse(String),
}

// ---------------------------------------------------------------------------
// Import
// ---------------------------------------------------------------------------

/// Accumulates a single SUMO lane while streaming.
struct LaneAcc {
    index: i32,
    width: f64,
    speed: f64,
}

/// Accumulates a single SUMO edge while streaming.
struct EdgeAcc {
    id: String,
    internal: bool,
    shape: Vec<(f64, f64)>,
    lane_shapes: Vec<Vec<(f64, f64)>>,
    lanes: Vec<LaneAcc>,
}

/// Import a SUMO `.net.xml` document and convert it to a [`Project`].
pub fn import_sumo_net(xml: &str) -> Result<Project, SumoError> {
    if xml.trim().is_empty() {
        return Err(SumoError::Parse("empty input".into()));
    }

    let mut reader = Reader::from_str(xml);
    let mut edges: Vec<EdgeAcc> = Vec::new();
    let mut current: Option<EdgeAcc> = None;

    loop {
        match reader
            .read_event()
            .map_err(|e| SumoError::Parse(e.to_string()))?
        {
            Event::Eof => break,
            Event::Start(e) => match e.name().as_ref() {
                b"edge" => current = Some(start_edge(&e)),
                b"lane" => add_lane(current.as_mut(), &e),
                _ => {}
            },
            Event::Empty(e) => match e.name().as_ref() {
                b"edge" => edges.push(start_edge(&e)),
                b"lane" => add_lane(current.as_mut(), &e),
                _ => {}
            },
            Event::End(e) => {
                if e.name().as_ref() == b"edge"
                    && let Some(edge) = current.take()
                {
                    edges.push(edge);
                }
            }
            _ => {}
        }
    }

    let roads: Vec<Road> = edges
        .into_iter()
        .filter(|e| !e.internal)
        .filter_map(edge_to_road)
        .collect();

    if roads.is_empty() {
        return Err(SumoError::Parse(
            "no drivable (non-internal) edges found".into(),
        ));
    }

    Ok(Project {
        name: "SUMO Import".into(),
        roads,
        ..Default::default()
    })
}

/// Begin accumulating an edge from its start/empty tag attributes.
fn start_edge(e: &BytesStart) -> EdgeAcc {
    let id = get_attr(e, b"id").unwrap_or_default();
    let function = get_attr(e, b"function").unwrap_or_default();
    let internal = function == "internal" || id.starts_with(':');
    let shape = get_attr(e, b"shape")
        .map(|s| parse_shape(&s))
        .unwrap_or_default();
    EdgeAcc {
        id,
        internal,
        shape,
        lane_shapes: Vec::new(),
        lanes: Vec::new(),
    }
}

/// Attach a lane (and its shape) to the in-progress edge, if any.
fn add_lane(edge: Option<&mut EdgeAcc>, e: &BytesStart) {
    let Some(edge) = edge else {
        return;
    };
    let index = get_attr(e, b"index")
        .and_then(|v| v.parse::<i32>().ok())
        .unwrap_or(edge.lanes.len() as i32);
    let width = get_attr(e, b"width")
        .and_then(|v| v.parse::<f64>().ok())
        .filter(|w| *w > 0.0)
        .unwrap_or(DEFAULT_LANE_WIDTH);
    let speed = get_attr(e, b"speed")
        .and_then(|v| v.parse::<f64>().ok())
        .unwrap_or(DEFAULT_SPEED);
    if let Some(shape) = get_attr(e, b"shape") {
        edge.lane_shapes.push(parse_shape(&shape));
    }
    edge.lanes.push(LaneAcc {
        index,
        width,
        speed,
    });
}

/// Convert an accumulated edge into a [`Road`], or `None` if it has no geometry.
fn edge_to_road(mut edge: EdgeAcc) -> Option<Road> {
    let centerline = if edge.shape.len() >= 2 {
        edge.shape.clone()
    } else {
        average_lane_shapes(&edge.lane_shapes)?
    };

    let geometries = polyline_to_geometries(&centerline);
    if geometries.is_empty() {
        return None;
    }
    let length: f64 = geometries.iter().map(|g| g.length).sum();

    let mut road = Road::new(edge.id.clone(), length);
    road.plan_view = geometries;
    road.speed = edge
        .lanes
        .iter()
        .map(|l| l.speed)
        .fold(None, |acc, s| Some(acc.map_or(s, |a: f64| a.max(s))));

    // Ensure deterministic lane order by SUMO index.
    edge.lanes.sort_by_key(|l| l.index);
    if edge.lanes.is_empty() {
        edge.lanes.push(LaneAcc {
            index: 0,
            width: DEFAULT_LANE_WIDTH,
            speed: DEFAULT_SPEED,
        });
    }

    let right: Vec<Lane> = edge
        .lanes
        .iter()
        .enumerate()
        .map(|(i, lane)| driving_lane(-(i as i32 + 1), lane.width))
        .collect();

    road.lane_sections.push(LaneSection {
        s: 0.0,
        single_side: false,
        render_hidden: false,
        left: Vec::new(),
        center: vec![center_lane()],
        right,
    });

    Some(road)
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

/// Export a [`Project`] to SUMO `.net.xml` text.
pub fn export_sumo_net(project: &Project) -> Result<String, SumoError> {
    let mut all_points: Vec<(f64, f64)> = Vec::new();
    let mut edges = String::new();
    let mut junctions = String::new();

    for road in &project.roads {
        let polyline = reference_polyline(road);
        if polyline.len() < 2 {
            continue;
        }
        all_points.extend_from_slice(&polyline);

        let shape = format_shape(&polyline);
        let speed = road.speed.unwrap_or(DEFAULT_SPEED);
        let length = road.length;
        let from = format!("{}_start", road.id);
        let to = format!("{}_end", road.id);

        edges.push_str(&format!(
            "  <edge id=\"{}\" from=\"{}\" to=\"{}\" priority=\"-1\" shape=\"{}\">\n",
            xml_escape(&road.id),
            xml_escape(&from),
            xml_escape(&to),
            shape,
        ));
        for (index, lane) in export_lane_widths(road).into_iter().enumerate() {
            edges.push_str(&format!(
                "    <lane id=\"{}_{}\" index=\"{}\" speed=\"{:.2}\" length=\"{:.2}\" width=\"{:.2}\" shape=\"{}\"/>\n",
                xml_escape(&road.id),
                index,
                index,
                speed,
                length,
                lane,
                shape,
            ));
        }
        edges.push_str("  </edge>\n");

        let (sx, sy) = polyline[0];
        let (ex, ey) = *polyline.last().unwrap();
        junctions.push_str(&format!(
            "  <junction id=\"{}\" type=\"priority\" x=\"{:.2}\" y=\"{:.2}\" incLanes=\"\" intLanes=\"\" shape=\"\"/>\n",
            xml_escape(&from), sx, sy,
        ));
        junctions.push_str(&format!(
            "  <junction id=\"{}\" type=\"priority\" x=\"{:.2}\" y=\"{:.2}\" incLanes=\"\" intLanes=\"\" shape=\"\"/>\n",
            xml_escape(&to), ex, ey,
        ));
    }

    let (min_x, min_y, max_x, max_y) = bounds(&all_points);

    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    out.push_str("<net version=\"1.16\" junctionCornerDetail=\"5\" limitTurnSpeed=\"5.50\">\n");
    out.push_str(&format!(
        "  <location netOffset=\"0.00,0.00\" convBoundary=\"{:.2},{:.2},{:.2},{:.2}\" origBoundary=\"{:.2},{:.2},{:.2},{:.2}\" projParameter=\"!\"/>\n",
        min_x, min_y, max_x, max_y, min_x, min_y, max_x, max_y,
    ));
    out.push_str(&edges);
    out.push_str(&junctions);
    out.push_str("</net>\n");
    Ok(out)
}

/// Lane widths to export, ordered to match SUMO lane indices (0 = id `-1`).
fn export_lane_widths(road: &Road) -> Vec<f64> {
    let Some(section) = road.lane_sections.first() else {
        return vec![3.5];
    };
    let mut lanes: Vec<&Lane> = section
        .right
        .iter()
        .filter(|l| l.lane_type.is_driving())
        .collect();
    // id -1 -> index 0, id -2 -> index 1, ...
    lanes.sort_by_key(|l| -l.id);
    if lanes.is_empty() {
        return vec![3.5];
    }
    lanes
        .iter()
        .map(|l| l.width.first().map(|w| w.a).unwrap_or(3.5))
        .collect()
}

// ---------------------------------------------------------------------------
// Geometry / lane helpers
// ---------------------------------------------------------------------------

/// Parse a SUMO `shape` attribute (`"x1,y1 x2,y2 ..."`) into points.
fn parse_shape(shape: &str) -> Vec<(f64, f64)> {
    shape
        .split_whitespace()
        .filter_map(|pair| {
            let mut it = pair.split(',');
            let x = it.next()?.parse::<f64>().ok()?;
            let y = it.next()?.parse::<f64>().ok()?;
            Some((x, y))
        })
        .collect()
}

/// Format points back into a SUMO `shape` string.
fn format_shape(points: &[(f64, f64)]) -> String {
    points
        .iter()
        .map(|(x, y)| format!("{x:.3},{y:.3}"))
        .collect::<Vec<_>>()
        .join(" ")
}

/// Average several equal-length lane shapes into a centerline, or fall back to
/// the middle lane shape when lengths differ.
fn average_lane_shapes(shapes: &[Vec<(f64, f64)>]) -> Option<Vec<(f64, f64)>> {
    let usable: Vec<&Vec<(f64, f64)>> = shapes.iter().filter(|s| s.len() >= 2).collect();
    if usable.is_empty() {
        return None;
    }
    let len = usable[0].len();
    if usable.iter().all(|s| s.len() == len) {
        let n = usable.len() as f64;
        let avg = (0..len)
            .map(|i| {
                let (sx, sy) = usable
                    .iter()
                    .fold((0.0, 0.0), |(ax, ay), s| (ax + s[i].0, ay + s[i].1));
                (sx / n, sy / n)
            })
            .collect();
        Some(avg)
    } else {
        Some(usable[usable.len() / 2].clone())
    }
}

/// Convert a polyline into a chain of OpenDRIVE line geometries.
fn polyline_to_geometries(points: &[(f64, f64)]) -> Vec<Geometry> {
    let mut geometries = Vec::new();
    let mut s = 0.0;
    for window in points.windows(2) {
        let (x0, y0) = window[0];
        let (x1, y1) = window[1];
        let (dx, dy) = (x1 - x0, y1 - y0);
        let length = (dx * dx + dy * dy).sqrt();
        if length < 1e-9 {
            continue;
        }
        geometries.push(Geometry {
            s,
            x: x0,
            y: y0,
            hdg: dy.atan2(dx),
            length,
            geo_type: GeometryType::Line,
        });
        s += length;
    }
    geometries
}

/// Recover the reference-line polyline (geometry vertices + final endpoint).
fn reference_polyline(road: &Road) -> Vec<(f64, f64)> {
    let mut points: Vec<(f64, f64)> = road.plan_view.iter().map(|g| (g.x, g.y)).collect();
    if let Some(last) = road.plan_view.last() {
        let end = evaluate_geometry(last, last.length);
        points.push((end.x, end.y));
    }
    points
}

/// Build a right-side driving lane with a constant width.
fn driving_lane(id: i32, width: f64) -> Lane {
    Lane {
        id,
        lane_type: LaneType::Driving,
        level: 0,
        render_hidden: false,
        link: None,
        width: vec![LaneWidth {
            s_offset: 0.0,
            a: width,
            b: 0.0,
            c: 0.0,
            d: 0.0,
        }],
        borders: Vec::new(),
        road_marks: Vec::new(),
    }
}

/// Build the mandatory zero-width center lane (id 0).
fn center_lane() -> Lane {
    Lane {
        id: 0,
        lane_type: LaneType::None,
        level: 0,
        render_hidden: false,
        link: None,
        width: Vec::new(),
        borders: Vec::new(),
        road_marks: Vec::new(),
    }
}

/// Axis-aligned bounds of all points (defaults to origin when empty).
fn bounds(points: &[(f64, f64)]) -> (f64, f64, f64, f64) {
    points.iter().fold(
        (0.0, 0.0, 0.0, 0.0),
        |(min_x, min_y, max_x, max_y), &(x, y)| {
            (min_x.min(x), min_y.min(y), max_x.max(x), max_y.max(y))
        },
    )
}

/// Read an attribute value as an owned `String`.
fn get_attr(e: &BytesStart, key: &[u8]) -> Option<String> {
    e.attributes()
        .flatten()
        .find(|a| a.key.as_ref() == key)
        .and_then(|a| a.unescape_value().ok().map(|c| c.into_owned()))
}

/// Minimal XML attribute escaping for exported identifiers.
fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE_NET: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<net version="1.16">
  <location netOffset="0.00,0.00" convBoundary="0.00,0.00,100.00,0.00" origBoundary="0,0,100,0" projParameter="!"/>
  <edge id="e1" from="A" to="B" priority="1" shape="0.00,0.00 50.00,0.00 100.00,0.00">
    <lane id="e1_0" index="0" speed="13.89" length="100.00" width="3.20" shape="0,-1.6 100,-1.6"/>
    <lane id="e1_1" index="1" speed="13.89" length="100.00" width="3.50" shape="0,1.6 100,1.6"/>
  </edge>
  <edge id=":J0_0" function="internal">
    <lane id=":J0_0_0" index="0" speed="5" length="2" shape="100,0 102,0"/>
  </edge>
  <junction id="A" type="priority" x="0.00" y="0.00" incLanes="" intLanes=""/>
</net>
"#;

    #[test]
    fn parse_shape_reads_coordinate_pairs() {
        let pts = parse_shape("0.0,1.0 2.5,-3.5 10,10");
        assert_eq!(pts, vec![(0.0, 1.0), (2.5, -3.5), (10.0, 10.0)]);
    }

    #[test]
    fn empty_input_is_an_error() {
        assert!(import_sumo_net("   ").is_err());
    }

    #[test]
    fn import_parses_edges_and_skips_internal() {
        let project = import_sumo_net(SAMPLE_NET).unwrap();
        assert_eq!(project.roads.len(), 1, "internal edge must be skipped");
        let road = &project.roads[0];
        assert_eq!(road.id, "e1");
        // Reference line: three vertices -> two line segments, total length 100.
        assert_eq!(road.plan_view.len(), 2);
        assert!((road.length - 100.0).abs() < 1e-6);
        assert!((road.plan_view[0].x).abs() < 1e-9);
        assert!((road.plan_view[1].x - 50.0).abs() < 1e-9);
    }

    #[test]
    fn import_reads_lane_count_and_widths() {
        let project = import_sumo_net(SAMPLE_NET).unwrap();
        let section = &project.roads[0].lane_sections[0];
        assert_eq!(section.right.len(), 2);
        assert!(section.left.is_empty());
        // index 0 -> id -1 width 3.2, index 1 -> id -2 width 3.5
        let lane_m1 = section.right.iter().find(|l| l.id == -1).unwrap();
        let lane_m2 = section.right.iter().find(|l| l.id == -2).unwrap();
        assert!((lane_m1.width[0].a - 3.2).abs() < 1e-9);
        assert!((lane_m2.width[0].a - 3.5).abs() < 1e-9);
    }

    #[test]
    fn export_emits_location_edge_and_junctions() {
        let project = import_sumo_net(SAMPLE_NET).unwrap();
        let xml = export_sumo_net(&project).unwrap();
        assert!(xml.contains("<location"));
        assert!(xml.contains("<edge id=\"e1\""));
        assert!(xml.contains("<lane id=\"e1_0\""));
        assert!(xml.contains("<junction id=\"e1_start\""));
        assert!(xml.contains("</net>"));
    }

    #[test]
    fn export_then_import_round_trips_geometry_and_lanes() {
        let original = import_sumo_net(SAMPLE_NET).unwrap();
        let xml = export_sumo_net(&original).unwrap();
        let reimported = import_sumo_net(&xml).unwrap();

        assert_eq!(reimported.roads.len(), original.roads.len());
        let a = &original.roads[0];
        let b = &reimported.roads[0];

        // Geometry polyline preserved.
        let pa = reference_polyline(a);
        let pb = reference_polyline(b);
        assert_eq!(pa.len(), pb.len());
        for ((ax, ay), (bx, by)) in pa.iter().zip(pb.iter()) {
            assert!((ax - bx).abs() < 1e-2, "x {ax} != {bx}");
            assert!((ay - by).abs() < 1e-2, "y {ay} != {by}");
        }

        // Lane count + widths preserved (ordered by id -1, -2, ...).
        let mut wa: Vec<f64> = a.lane_sections[0]
            .right
            .iter()
            .map(|l| l.width[0].a)
            .collect();
        let mut wb: Vec<f64> = b.lane_sections[0]
            .right
            .iter()
            .map(|l| l.width[0].a)
            .collect();
        wa.sort_by(|x, y| x.partial_cmp(y).unwrap());
        wb.sort_by(|x, y| x.partial_cmp(y).unwrap());
        assert_eq!(wa.len(), wb.len());
        for (x, y) in wa.iter().zip(wb.iter()) {
            assert!((x - y).abs() < 1e-2, "width {x} != {y}");
        }
    }

    #[test]
    fn edge_without_shape_uses_lane_shapes() {
        let net = r#"<net version="1.16">
  <edge id="e2" from="A" to="B">
    <lane id="e2_0" index="0" speed="10" length="10" width="3.0" shape="0,0 10,0"/>
  </edge>
</net>"#;
        let project = import_sumo_net(net).unwrap();
        assert_eq!(project.roads.len(), 1);
        let road = &project.roads[0];
        assert_eq!(road.plan_view.len(), 1);
        assert!((road.length - 10.0).abs() < 1e-6);
        assert_eq!(road.lane_sections[0].right.len(), 1);
    }

    #[test]
    fn network_without_drivable_edges_errors() {
        let net = r#"<net version="1.16">
  <edge id=":J_0" function="internal">
    <lane id=":J_0_0" index="0" speed="5" length="2" shape="0,0 2,0"/>
  </edge>
</net>"#;
        assert!(import_sumo_net(net).is_err());
    }
}
