style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/lin51kevin/worldeditor
options:
  commits:
    filters:
      Type:
        - feat
        - perf
        - fix
        - refactor
        - test
        - ci
  commit_groups:
    title_maps:
      feat: Features
      perf: Performance
      fix: Fixes
      refactor: Refactor
      test: Tests
      ci: CI
    sort_by: Custom
    title_order:
      - CI
      - Tests
      - Refactor
      - Fixes
      - Performance
      - Features
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s,/]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
