// Type declarations for the we-wasm module (generated by wasm-bindgen)
declare module '../../wasm/pkg/we_wasm' {
  export default function init(): Promise<void>;

  // OpenDRIVE I/O
  export function parse_opendrive(xml: string): any; // Returns JS object from wasm-bindgen
  export function write_opendrive(project_json: string): string;

  // GIS coordinate transforms
  export function wgs84_to_gcj02(lat: number, lon: number, alt: number): { lat: number; lon: number; alt: number };
  export function gcj02_to_wgs84(lat: number, lon: number, alt: number): { lat: number; lon: number; alt: number };
  export function geo_to_utm(lat: number, lon: number, alt: number): { easting: number; northing: number; zone: number; is_northern: boolean; alt: number };
  export function utm_to_geo(easting: number, northing: number, zone: number, is_northern: boolean, alt: number): { lat: number; lon: number; alt: number };

  // Render vertex generation (returns Float32Array)
  export function generate_road_vertices(project_json: string, sample_step: number): Float32Array;
  export function generate_single_road_vertices(road_json: string, sample_step: number, r: number, g: number, b: number, a: number): Float32Array;
  export function generate_single_junction_vertices(project_json: string, junction_id: string, r: number, g: number, b: number, a: number): Float32Array;
  export function generate_junction_vertices(project_json: string): Float32Array;
  export function generate_lane_line_vertices(project_json: string, sample_step: number): Float32Array;
  export function generate_center_line_vertices(project_json: string, sample_step: number): Float32Array;
  export function generate_signal_paint_vertices(project_json: string, sample_step: number): Float32Array;
  export function generate_object_vertices(project_json: string): Float32Array;

  // Picking
  export function pick_road_at_point(project_json: string, x: number, y: number, threshold: number): string | null;
  export function pick_junction_at_point(project_json: string, x: number, y: number, threshold: number): string | null;
  export function pick_signal_at_point(project_json: string, x: number, y: number, threshold: number): { roadId: string; signalId: string } | null;
  export function pick_object_at_point(project_json: string, x: number, y: number, threshold: number): { roadId: string; objectId: string } | null;

  // Elevation
  export function query_elevation(road_json: string, s: number): { elevation: number; grade: number; grade_pct: number };
  export function add_elevation_point(project_json: string, road_id: string, s: number, height: number): string;
  export function delete_elevation_point(project_json: string, road_id: string, s: number, tolerance: number): string;
  export function smooth_elevation(project_json: string, road_id: string, iterations: number): string;

  // Snapping
  export function snap_point(project_json: string, x: number, y: number, config_json: string, exclude_road_id?: string): { x: number; y: number; snapped: boolean; snap_type: string; target_id: string | null; contact_point: string | null };
  export function get_road_endpoint_tangent(project_json: string, road_id: string, contact_point: string): { x: number; y: number; hdg: number } | null;

  // Measurement
  export function measure_distance(x1: number, y1: number, z1: number, x2: number, y2: number, z2: number): { straight: number; horizontal: number; vertical: number };
  export function measure_angle(x1: number, y1: number, x2: number, y2: number, x3: number, y3: number): { radians: number; degrees: number };
  export function measure_area(points_json: string): { area: number; perimeter: number };
  export function measure_road_length(road_json: string, s_start: number, s_end: number): number;

  // Road templates
  export function get_road_templates(): Array<{ id: string; name: string; left_lanes: number; right_lanes: number; lane_width: number }>;

  // Spline editing
  export function create_road_from_spline(project_json: string, road_id: string, spline_json: string, template_id: string, mode: string): string;
  export function road_to_spline(road_json: string, sample_step: number): string;
  export function move_spline_knot(spline_json: string, knot_index: number, x: number, y: number, z: number): string;
  export function spline_to_geometries(spline_json: string, mode: string): string;
}
