// Type declarations for the we-wasm module (generated by wasm-bindgen)
// NOTE: Import types cannot be used in ambient module declarations,
// so we define inline interfaces for WASM return types.

/** OpenDRIVE project structure as returned from WASM parse functions. */
interface WasmProject {
  name: string;
  header: Record<string, unknown>;
  roads: Array<Record<string, unknown>>;
  junctions: Array<Record<string, unknown>>;
  signals: Array<Record<string, unknown>>;
  [key: string]: unknown;
}

/** Sprite instance data for billboard rendering (traffic lights, road signs). */
interface SpriteInstanceRaw {
  pos: [number, number, number];
  signal_type: string;
  subtype: string;
  w: number;
  h: number;
  value: string;
}

/** Paint instance data for ground-aligned textured quads (road arrows). */
interface PaintInstanceRaw {
  pos: [number, number, number];
  subtype: string;
  w: number;
  h: number;
  rot: number;
}

/** Result from generate_sprite_data WASM function. */
interface SpriteDataResult {
  sprites: SpriteInstanceRaw[];
  paints: PaintInstanceRaw[];
}

declare module '../../wasm/pkg/we_wasm' {
  export default function init(): Promise<void>;

  // OpenDRIVE I/O
  export function parse_opendrive(xml: string): WasmProject;
  export function write_opendrive(project_json: string): string;

  // GIS coordinate transforms
  export function wgs84_to_gcj02(lat: number, lon: number, alt: number): { lat: number; lon: number; alt: number };
  export function gcj02_to_wgs84(lat: number, lon: number, alt: number): { lat: number; lon: number; alt: number };
  export function geo_to_utm(lat: number, lon: number, alt: number): { easting: number; northing: number; zone: number; is_northern: boolean; alt: number };
  export function utm_to_geo(easting: number, northing: number, zone: number, is_northern: boolean, alt: number): { lat: number; lon: number; alt: number };

  // Render vertex generation (returns Float32Array)
  export function generate_single_road_vertices(road_json: string, sample_step: number, r: number, g: number, b: number, a: number): Float32Array;
  export function generate_single_junction_vertices(project_json: string, junction_id: string, r: number, g: number, b: number, a: number): Float32Array;
  export function generate_junction_vertices(project_json: string): Float32Array;
  export function generate_lane_line_vertices(project_json: string, sample_step: number): Float32Array;
  export function generate_center_line_vertices(project_json: string, sample_step: number): Float32Array;
  export function generate_signal_paint_vertices(project_json: string, sample_step: number): Float32Array;
  export function generate_object_vertices(project_json: string): Float32Array;
  export function generate_object_vertices_cached(): Float32Array;
  export function generate_sprite_data(project_json: string): SpriteDataResult;

  // Picking
  export function pick_road_at_point(project_json: string, x: number, y: number, threshold: number): string | null;
  export function pick_junction_at_point(project_json: string, x: number, y: number, threshold: number): string | null;
  export function pick_signal_at_point(project_json: string, x: number, y: number, threshold: number): { roadId: string; signalId: string } | null;
  export function pick_object_at_point(project_json: string, x: number, y: number, threshold: number): { roadId: string; objectId: string } | null;

  // Elevation
  export function query_elevation(road_json: string, s: number): { elevation: number; grade: number; grade_pct: number };
  export function add_elevation_point(project_json: string, road_id: string, s: number, height: number): string;
  export function delete_elevation_point(project_json: string, road_id: string, s: number, tolerance: number): string;
  export function smooth_elevation(project_json: string, road_id: string, iterations: number): string;

  // Snapping
  export function snap_point(project_json: string, x: number, y: number, config_json: string, exclude_road_id?: string): { x: number; y: number; snapped: boolean; snap_type: string; target_id: string | null; contact_point: string | null };
  export function get_road_endpoint_tangent(project_json: string, road_id: string, contact_point: string): { x: number; y: number; hdg: number } | null;

  // Measurement
  export function measure_distance(x1: number, y1: number, z1: number, x2: number, y2: number, z2: number): { straight: number; horizontal: number; vertical: number };
  export function measure_angle(x1: number, y1: number, x2: number, y2: number, x3: number, y3: number): { radians: number; degrees: number };
  export function measure_area(points_json: string): { area: number; perimeter: number };
  export function measure_road_length(road_json: string, s_start: number, s_end: number): number;

  // Road templates
  export function get_road_templates(): Array<{ id: string; name: string; left_lanes: number; right_lanes: number; lane_width: number }>;

  // Spline editing
  export function create_road_from_spline(project_json: string, road_id: string, spline_json: string, template_id: string, mode: string): string;
  export function road_to_spline(road_json: string, sample_step: number): string;
  export function move_spline_knot(spline_json: string, knot_index: number, x: number, y: number, z: number): string;
  export function spline_to_geometries(spline_json: string, mode: string): string;

  // Lanelet2 I/O
  export function import_from_lanelet2(xml: string): WasmProject;
  export function export_to_lanelet2(project_json: string): string;
  export function import_from_dxf(dxf: string): WasmProject;
  export function export_to_dxf(project_json: string): string;
  export function import_from_shapefile(bytes: Uint8Array): WasmProject;
  export function export_to_shapefile(project_json: string): Uint8Array;
  export function import_from_mif(mif: string): WasmProject;
  export function export_to_mif(project_json: string): string;
  export function import_from_nio(bytes: Uint8Array): WasmProject;
  export function export_to_nio(project_json: string): Uint8Array;

  // GIS extended
  export function geodetic_to_ecef(lat_deg: number, lon_deg: number, alt_m: number): { x: number; y: number; z: number };
  export function ecef_to_geodetic(x: number, y: number, z: number): { lat: number; lon: number; alt: number };
  export function geo_to_mgrs(lat_deg: number, lon_deg: number, precision: number): string;
  export function parse_proj4_crs(proj4_str: string): Record<string, string>;
  export function parse_wkt_crs(wkt_str: string): { crs_type: string; name: string; epsg: number | null };

  // Project cache (spatial index + JSON avoidance on mousemove)
  export function set_project_cache(project_json: string): void;
  export function update_cached_road(road_json: string): void;
  export function invalidate_project_cache(): void;
  export function has_project_cache(): boolean;

  // Cached picking (uses project cache — no JSON per call)
  export function pick_road_at_point_cached(x: number, y: number, threshold: number): string | null;
  export function pick_junction_at_point_cached(x: number, y: number, threshold: number): string | null;
  export function pick_lane_at_point_cached(x: number, y: number, threshold: number): { roadId: string; sectionIndex: number; laneId: number } | null;
  export function pick_signal_at_point_cached(x: number, y: number, threshold: number): { roadId: string; signalId: string } | null;
  export function pick_object_at_point_cached(x: number, y: number, threshold: number): { roadId: string; objectId: string } | null;
  export function snap_point_cached(x: number, y: number, config_json: string, exclude_road_id?: string): { x: number; y: number; snapped: boolean; snap_type: string; target_id: string | null; contact_point: string | null };
  export function snap_point_on_road(road_json: string, world_x: number, world_y: number): { s: number; t: number; hdg: number };

  // World position queries (cached)
  export function get_signal_world_pos(project_json: string, road_id: string, signal_id: string): { x: number; y: number } | null;
  export function get_object_world_pos(project_json: string, road_id: string, object_id: string): { x: number; y: number } | null;
  export function get_signal_world_pos_cached(road_id: string, signal_id: string): { x: number; y: number } | null;
  export function get_object_world_pos_cached(road_id: string, object_id: string): { x: number; y: number } | null;
  export function get_lane_world_pos_cached(road_id: string, section_index: number, lane_id: number): { x: number; y: number } | null;

  // Vertex generation (additional)
  export function generate_road_vertices(project_json: string, sample_step: number, color_mode: string): Float32Array;
  export function generate_road_vertices_cached(sample_step: number, color_mode: string): Float32Array;
  export function generate_single_road_surface_vertices_cached(road_id: string, sample_step: number, color_mode: string): Float32Array;
  export function generate_lane_boundary_vertices(project_json: string, sample_step: number): Float32Array;
  export function generate_bridge_tunnel_vertices(project_json: string): Float32Array;
  export function generate_single_signal_vertices(project_json: string, road_id: string, signal_id: string, r: number, g: number, b: number, a: number): Float32Array;
  export function generate_single_signal_vertices_cached(road_id: string, signal_id: string, r: number, g: number, b: number, a: number): Float32Array;
  export function generate_single_object_vertices(project_json: string, road_id: string, object_id: string, r: number, g: number, b: number, a: number): Float32Array;
  export function generate_single_object_vertices_cached(road_id: string, object_id: string, r: number, g: number, b: number, a: number): Float32Array;

  // Junction operations
  export function auto_build_junction_connectors(project_json: string, junction_id: string): string;

  // I/O bridge functions
  export function import_roads_from_csv(csv: string, options_json: string): string;
  export function export_roads_to_csv(project_json: string): string;
  export function export_project_to_obj(project_json: string): string;
  export function import_signals_from_json(json: string): string;
  export function export_to_hdmap_xml(project_json: string): string;

  // Validation
  export function validate_project(project_json: string): string;
  export function project_is_valid(project_json: string): boolean;
  export function validate_topology(project_json: string): string;
  export function repair_topology(project_json: string): { project: string; actions: string[] };

  // Road transform operations
  export function translate_road(project_json: string, road_id: string, dx: number, dy: number, dz: number): string;
  export function rotate_road(project_json: string, road_id: string, pivot_x: number, pivot_y: number, angle_rad: number): string;
  export function compute_road_width(road_json: string, s: number): { left: number; right: number };
  export function sample_lane_boundary(road_json: string, section_s: number, lane_id: number, step: number): string;

  // Junction extended operations
  export function compute_junction_area(project_json: string, junction_id: string): { id: string; center: [number, number]; boundary: Array<[number, number]>; area: number } | null;
  export function optimize_junction(project_json: string, junction_id: string): string | null;
  export function get_junction_arms(project_json: string, junction_id: string): string;
  export function point_in_junction(project_json: string, junction_id: string, x: number, y: number): boolean;
  export function generate_default_lane_section(s: number, n_lanes_per_side: number, lane_width: number, with_shoulder: boolean): string;

  // Spline/geometry utilities
  export function compute_soft_selection(spline_json: string, selected_index: number, radius: number, falloff_type: string): string;
  export function pick_spline_knot(spline_json: string, x: number, y: number, threshold: number): { index: number; distance: number } | null;

  // GIS affine transform
  export function fit_affine_from_gcps(gcps_json: string): { a00: number; a01: number; b0: number; a10: number; a11: number; b1: number };
  export function apply_affine_transform(transform_json: string, source_x: number, source_y: number): { x: number; y: number };

  // Spatial query
  export function spatial_query_point(project_json: string, x: number, y: number, radius: number): Array<{ id: string; kind: string; aabb: unknown }>;

  // Road mesh pipeline
  export function generate_road_mesh_from_json(road_json: string, sample_step: number): string;

  // I/O
  export function export_signals_to_json(project_json: string): string;

  // Point cloud (WASM path — desktop uses native, web uses these)
  export function load_point_cloud(bytes: Uint8Array, format: string): number;
  export function free_point_cloud(handle: number): void;
  export function point_cloud_summary(handle: number): { count: number; origin: [number, number, number]; min: [number, number, number]; max: [number, number, number]; has_intensity: boolean; has_rgb: boolean };
  export function point_cloud_render_buffer(handle: number, color_mode: string, max_points: number): Float32Array;
  export function point_cloud_extract_ground(handle: number, config_json: string): unknown;
  export function point_cloud_sample_ground(handle: number, x: number, y: number): number | undefined;
  export function point_cloud_extract_markings(handle: number, config_json: string): unknown;
  export function point_cloud_vectorize(handle: number, polylines_json: string, config_json: string, use_ground: boolean): unknown;

  // Version
  export function version(): string;
}
